### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by aclarembeau** [jagregory/atom-pandoc-preview#25]
So, because the screenshot is worth a thousand words (not really sure it's a good ideomatic expression but for me it sound good)
![selection_037](https://cloud.githubusercontent.com/assets/10834626/9689203/ca2fb26c-5334-11e5-87b4-76ed49562573.png)

I don't know why it does that on my Linux Mint 17.2 Raphaella but I'd be very happy to help you to discover the origin of the problem :) (it does that to all my files)
PS2: My computer language is French; maybe it's the origin of the problem?

**Comment by aclarembeau** [comment]
After some time, I discovered that: 
- my file is well encoded 
- the generated HTML file is good but not well shown 

So, I found a solution by adding --ascii to the pandoc command line. 
It avoids the problem but is not a good solid solution

**Comment by phiresky** [comment]
I had the same issue, but I found https://github.com/Galadirith/markdown-preview-plus instead, which as far as I can tell does everything this plugin does, and also has better live updating.

@jagregory I'd suggest deprecating this project in favor of that (if I did not miss something) and maybe adding links to the other project, because this is the first result when searching for `pandoc`
